# Generated by Django 2.2.2 on 2019-07-09 13:53

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Hotels',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('hotel_id', models.AutoField(primary_key=True, serialize=False)),
                ('address', models.CharField(max_length=300, null=True)),
                ('city', models.CharField(max_length=30, null=True)),
                ('state', models.CharField(max_length=30, null=True)),
                ('country', models.CharField(max_length=30, null=True)),
                ('phone_number', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(code='invalid_cell', message='Enter a valid phone number', regex='^[1-9]{1}[0-9]{9}$')])),
                ('email', models.EmailField(blank=True, max_length=70, null=True, unique=True)),
                ('description', models.CharField(default='Hello', max_length=1000)),
                ('lat', models.FloatField(default=0)),
                ('long', models.FloatField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Rooms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_type', models.CharField(choices=[('Room', 'Room'), ('Standard Double Room', 'Standard Double Room'), ('Standard Family Room', 'Standard Family Room'), ('Deluxe Double Room', 'Deluxe Double Room')], default='Room', max_length=30)),
                ('room_fac', models.CharField(choices=[('AC', 'AC'), ('Non-AC', 'Non-AC')], default='Non-AC', max_length=8)),
                ('price', models.FloatField()),
                ('cost', models.FloatField()),
                ('availability', models.IntegerField(default=0)),
                ('capacity', models.IntegerField(default=0)),
                ('hotel_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel_booking.Hotels')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='hotels')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='hotel_booking.Hotels')),
            ],
        ),
        migrations.CreateModel(
            name='Hotel_Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=10)),
                ('age', models.IntegerField()),
                ('room_type', models.CharField(default='Room', max_length=30)),
                ('room_fac', models.CharField(default='Non-AC', max_length=8)),
                ('fromdate', models.DateField()),
                ('fromtime', models.CharField(max_length=20)),
                ('todate', models.DateField()),
                ('totime', models.CharField(max_length=20)),
                ('booking_id', models.CharField(max_length=50)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel_booking.Hotels')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(blank=True)),
                ('rating', models.IntegerField(default=0)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel_booking.Hotels')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
